@baseUrl = http://127.0.0.1:8000
@contentType = application/json
@authToken = xxx

### Sign Up
POST {{baseUrl}}/auth/signup/
Content-Type: {{contentType}}

{
    "email": "davie@mail.com",
    "password": "Pass123456!",
    "username": "davie",
    "phone_number": "+254712345678",
    "address": "Nairobi, Kenya"
}


### Login
POST {{baseUrl}}/auth/login/
Content-Type: {{contentType}}

{
    "username": "arthur",
    "password": "Pass123!",
    "email": "arthur@mail.com"
}

### Test Token Authentication
GET {{baseUrl}}/auth/test_token/
Content-Type: {{contentType}}
Authorization: Token {{authToken}}

### Invalid Login Test
POST {{baseUrl}}/auth/login/
Content-Type: {{contentType}}

{
    "username": "wronguser",
    "password": "wrongpass"
}

### Test Without Token (Should Return 401)
GET {{baseUrl}}/auth/test_token/
Content-Type: {{contentType}}

### Optional: Sign Up with Full User Details
POST {{baseUrl}}/auth/signup/
Content-Type: {{contentType}}

{
    "username": "adam2",
    "password": "Pass1234!",
    "email": "adam2@mail.com",
    "first_name": "Adam",
    "last_name": "Smith"
}

### Test Token After Login
# Remember to replace {{authToken}} with the token received from login response
GET {{baseUrl}}/auth/test_token/
Content-Type: {{contentType}}
Authorization: Token {{authToken}}
